service: mmb-mark-utils

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
  
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:*'
          Resource: 'arn:aws:s3:::device-daily-log/*'

functions:
  dailyCheckDeviceDetails:
    handler: lib/mmbDevices.dailyCheck
    events:
      - schedule: cron(0 3 ? * * *)
